#!/bin/ksh

# Use exa instead of ls if available
if command -v exa > /dev/null 2>&1
	then alias ls="exa -Fbg"
	else alias ls="ls -Fh"
fi

# Run something N amount of times
run() {
	[[ $# -lt 2 ]] && return 1
	local i=0
	local n=$1; shift
	until [[ $i -eq $n ]]
	do
		eval "$@"
		i=$((i+1))
	done
}
