#!/bin/ksh

alias ls="ls -Fh --color=auto"
alias grep="grep --color=auto"

# Run something N amount of times
run() {
	[[ $# -lt 2 ]] && return 1
	local i=0
	local n=$1; shift
	until [[ $i -eq $n ]]
	do
		eval "$@"
		i=$((i+1))
	done
}

cache-repo() {
	doas repoman -j 4 manifest
	repoman -j 4 full
	doas egencache --update --repo "${PWD##*/}" -j 4
}
