#!/bin/sh

# Place this file in /etc/profile.d
[ ! "$(id -u)" = "1000" ] || [ ! "${0##*/}" = "-ksh" ] && return 0

# Add local bin dirs to path
PATH="$HOME/bin:$HOME/opt/bin:$PATH"

# Set XDG variables
XDG_CACHE_HOME="$HOME/tmp/cache"
XDG_CONFIG_HOME="$HOME/cfg"
XDG_DATA_HOME="$HOME/data"

# KSH specific variables
ENV="$XDG_CONFIG_HOME/loksh/rc"
HISTCONTROL="ignoredups:ignorespace"
HISTFILE="$XDG_CACHE_HOME/loksh_history"
HISTSIZE=

# Prevent $HOME pollution
LESSHISTFILE="$XDG_CACHE_HOME/less_history"
GNUPGHOME="$XDG_DATA_HOME/gnupg"
PASSWORD_STORE_DIR="$HOME/doc/.pws"

# Set default commands
VISUAL="kak"
EDITOR="kak"
PAGER="less"

# Export all the variables
export PATH XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME ENV HISTCONTROL \
       HISTFILE HISTSIZE LESSHISTFILE GNUPGHOME PASSWORD_STORE_DIR VISUAL \
       EDITOR PAGER

# Clear tty after login
clear
