shadow-radius = 6;
shadow-opacity = 0.4;
shadow-offset-x = 6;
shadow-offset-y = 6;
fade-delta = 2;
shadow = true;
fading = true;

log-level = "INFO";
#log-file = "/home/ye/.cache/compton.log";

refresh-rate = 144;
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;

wintypes:
{
	dnd = { shadow = false; }
	dock = { shadow = false; }
	dropdown_menu = { shadow=false; }
	popup_menu = { shadow=false; }
	tooltip = { fade = true; shadow = false; opacity = 0.8; focus = true; };
	utility = { fade = true; shadow = false; }
};
