=sys-devel/llvm-10.0.0 *FLAGS-="-fipa-pta" # Causes errors when built with AMDGPU target

# Needs the same work arounds as llvm
sys-devel/llvm-roc *FLAGS-="${SEMINTERPOS}"

# LLVM can't cross link with GCC
net-news/newsboat *FLAGS+=-ffat-lto-objects
