# Segfaults
sys-devel/llvm:10 *FLAGS-=-flto*

# needed for rocm-opencl-runtime: requires same workarounds as llvm
sys-devel/llvm-roc *FLAGS-="${SEMINTERPOS}"

# needed for app-emulation/qemu
net-libs/libiscsi *FLAGS-=-fno-semantic-interposition

# needed for games-action/minecraft-launcher
gnome-base/gconf NOCOMMON_OVERRIDE_LIBTOOL=yes
