# clang doesn't recognize -ffat-lto-objects
*/* *FLAGS-="-ffat-lto-objects" # 19 August 2020
# clang doesn't recognize -fno-ipa-cp-clone
*/* *FLAGS-="-fno-ipa-cp-clone" # 2 September 2020

# ld.lld: error: undefined symbol: entrypointFunctions
media-libs/libglvnd *FLAGS-="-flto*" # 18 August 2020
# ld.lld: error: TLS attribute mismatch: _glapi_tls_Dispatch
media-libs/mesa *FLAGS-="-flto*" # 18 August 2020
# ld.lld: error: -plugin-opt=Os: number expected, but got 's'
net-print/cups *FLAGS-="-flto*" # 19 August 2020
