=sys-devel/llvm-10.0.1 *FLAGS-="-fipa-pta" # Runtime Errors

sys-devel/llvm-roc *FLAGS-="${SEMINTERPOS}" # Needs the same work arounds as llvm

net-news/newsboat *FLAGS+=-ffat-lto-objects # LLVM can't cross link with GCC
