#!/usr/bin/env bash
alias {l,ls}="ls -F --color=auto"
alias la="l -A"
alias ll="l -lh"
alias lla="l -lAh"

alias c="clear"
alias q="exit"
alias qe="qlist -IR | grep -v ::gentoo"

run() {
    [[ $# -lt 2 ]] && return 1
    for ((i=1; i<=$1; i++))
    do
	eval "${@:2}"
    done
}
