#!/usr/bin/env bash

app_name="MPD Toggle Repeat"
summary="Repeat: $(mpc repeat | awk NR==3'{print $4}')"
body="$(mpc -q current)"

dunstify -a "$app_name" \
	-t 4000 \
	-r 1 \
	"$summary" \
	"$body"
