#!/usr/bin/env sh

# Script to stop MPD and display a notification
# Requires:
#	libnotify or dunstify
#	mpd
#	mpc

app_name="MPD Status"
summary="Stopped"
body="MPD has been stopped"

mpc stop

sleep .01
if command -v dunstify; then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" \
		"${body}"
else
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" \
		"${body}"
fi

