#!/usr/bin/env sh

app_name="MPD Volume"
summary="Decreasing: $(mpc volume | awk '{print $2}')"

mpc volume -2

if command -v dunstify
then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}"
elif command -v notify-send
then
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}"
else
	echo "dunstify or libnotify not found"
	exit 1
fi
