#!/usr/bin/env sh

app_name="MPD Info"

if ! [ "$(mpc current)" ]
then
	summary="[Stopped]"
else
	if mpc status | grep -q paused
	then
		play="[Paused]"
	fi

	if [ "$(mpc crossfade | awk '{print $2}')" -gt 0 ]
	then
		fade="x"
	fi

	if [ "$(mpc status | awk NR==3'{print $4}')" = "on" ]
	then
		re="r"
	fi

	if [ "$(mpc status | awk NR==3'{print $6}')" = "on" ]
	then
		ran="z"
	fi

	if [ "$(mpc status | awk NR==3'{print $8}')" = "on" ]
	then
		sin="s"
	fi

	vol="[$(mpc volume | awk '{print $2}')]"
	time="[$(mpc | awk NR==2'{print $3}')]"
	num="[$(mpc listall | wc -l)]"

	summary="${num} [${re}${ran}${sin}${fade}] ${vol} ${time} ${play}"
	body="$(mpc current)"
fi

if command -v dunstify
then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" \
		"${body}"
elif command -v notify-send
then
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" \
		"${body}"
else
	echo "dunstify or libnotify not found"
	exit 1
fi
