#!/usr/bin/env sh

# Notification Script to display information about MPD
# Requires:
#	libnotify or dunstify
#	mpc
#	mpd

app_name="MPD Status"

if ! [ "$(mpc current)" ]; then
	summary="MPD: Stopped"
	body="MPD has been stopped"
else
	if mpc status | grep -q paused; then
		PAUSE="[Paused]"
	else
		PAUSE=""
	fi

	VOL="[$(mpc volume | awk '{print $2}')]"

	if [ "$(mpc crossfade | awk '{print $2}')" -gt 0 ]; then
		CFADE="x"
	else
		CFADE=""
	fi

	if [ "$(mpc status | awk NR==3'{print $4}')" = "on" ]; then
		RE="r"
	else
		RE=""
	fi

	if [ "$(mpc status | awk NR==3'{print $6}')" = "on" ]; then
		RAN="z"
	else
		RAN=""
	fi

	if [ "$(mpc status | awk NR==3'{print $8}')" = "on" ];then
		SIN="s"
	else
		SIN=""
	fi

	SONGNUM="[$(mpc listall | wc -l)]"

	summary="${SONGNUM} [${RE}${RAN}${SIN}${CFADE}] ${VOL} ${PAUSE}"
	body="$(mpc current)"

fi

if command -v dunstify; then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" \
		"${body}"
else
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" \
		"${body}"
fi
