#!/usr/bin/env sh

# Script to Toggle music and display a notification
# Requires:
#	libnotify or dunstify
#	mpc
#	mpd

app_name="MPD Status"

if mpc toggle | grep -q paused; then
	summary="MPD Paused"
	body="$(mpc current)"
else
	summary="MPD Playing"
	body="$(mpc current)"
fi

if command -v dunstify; then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" \
		"${body}"
else
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" \
		"${body}"
fi
