#!/usr/bin/env bash

if mpc toggle | grep -q paused
then
	app_name="MPD Paused"
	#summary="$(mpc current)"
else
	app_name="MPD Playing"
	summary="$(mpc current)"
fi

dunstify -a "${app_name}" \
	-t 4000 \
	-r 1 \
	"${summary}" 
