#!/usr/bin/env sh

if mpc toggle | grep -q paused
then
	app_name="MPD Paused"
	summary="$(mpc current)"
else
	app_name="MPD Playing"
	summary="$(mpc current)"
fi

if command -v dunstify
then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" 
elif command -v notify-send
then
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" 
else
	echo "dunstify/notify-send not found"
	exit 1
fi
