Section "Monitor"
	Identifier	"Monitor0"
	Modeline 	"1920x1080@144" 325.08 1920 1944 1976 2056 1080 1083 1088 1098 +HSync +VSync
	Option 		"PreferredMode" "1920x1080@144"
	DisplaySize	531 299
EndSection

Section "Device"
	Identifier	"Device0"
	Driver		"amdgpu"
EndSection

Section "Screen"
	Identifier	"Screen0"
	Device		"Device0"
	Monitor		"Monitor0"
	DefaultDepth	24
	SubSection	"Display"
		Depth	24
	EndSubSection
EndSection
