#!/usr/bin/env sh

# Notification Script for MPD
# Requires:
#	libnotify or dunstify
#	mpc

app_name="MPD Status"
icon="${HOME}/.dotfiles/notificationscripts/icons/music-white.png"

if pidof mpd
then
	if ! [ "$(mpc current)" ]
	then
		summary="MPD: Stopped"
		body="MPD has been stopped"
	elif mpc status | grep -q "paused"
	then
		summary="MPD: Paused"
		body="$(mpc current)"
	else
		summary="MPD: Playing"
		body="$(mpc current)"
	fi
else
	summary="MPD: N/A"
	body="MPD not running"
fi

if command -v dunstify
then
	dunstify \
		-a "${app_name}" \
		-t 4000 \
		-i "${icon}" \
		-r 13596705 \
		"${summary}" \
		"${body}"
else
	notify-send \
		-t 4000 \
		-a "${app_name}" \
		-i "${icon}" \
		"${summary}" \
		"${body}"
fi
