#!/usr/bin/env sh
# Notification Script for MPD

app_name="Time and Date"
icon="${HOME}/.dotfiles/notificationscripts/icons/timedate-white.png"

summary="Time: $(date +'%R')"
body="Date: $(date +'%a %d %b %Y')"

if command -v dunstify
then
	dunstify \
		-a "${app_name}" \
		-t 4000 \
		-i "${icon}" \
		-r 13596705 \
		"${summary}" \
		"${body}"
else
	notify-send \
		-t 4000 \
		-a "${app_name}" \
		-i "${icon}" \
		"${summary}" \
		"${body}"
fi
