#!/usr/bin/env sh

# Notification Script for Volume
# Requires:
#	libnotify or dunstify
#	Pulseaudio

app_name="Audio Status"
icon="${HOME}/.dotfiles/global/noti/icons/audio.png"

speaker_volume="$(pactl list sinks | grep Volume | awk NR==1'{print $5}')"
speaker_mute="$(pactl list sinks | grep 'Mute: yes' | awk NR==1'{print $2}')"

microphone_volume="$(pactl list sources | grep Volume | awk NR==1'{print $5}')"
microphone_mute="$(pactl list sources | grep 'Mute: yes' | awk NR==1'{print $2}')"

if [ "${speaker_mute}" = 'yes' ]
then
	summary="Speakers: MUTED ${speaker_volume}"
else
	summary="Speakers: ${speaker_volume}"
fi

if [ "${microphone_mute}" = 'yes' ]
then
	body="Microphone: MUTED ${microphone_volume}"
else
	body="Microphone: ${microphone_volume}"
fi

if command -v dunstify
then
	dunstify \
		-a "${app_name}" \
		-t 4000 \
		-i "${icon}" \
		-r 13596705 \
		"${summary}" \
		"${body}"
else
	notify-send \
		-t 4000 \
		-a "${app_name}" \
		-i "${icon}" \
		"${summary}" \
		"${body}"
fi
