CHOST="x86_64-pc-linux-gnu"
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
MAKEOPTS="-j12"

PORTDIR="/usr/portage"
DISTDIR="/usr/portage/distfiles"
PKGDIR="/usr/portage/packages"

FEATURES="ccache"
CCACHE_SIZE="10G"

USE="-bluetooth -consolekit -cups -kmod -systemd
X acpi alsa bash-completion dbus elogind libressl pulseaudio udev vaapi vdpau vulkan wayland"

ACCEPT_KEYWORDS="~amd64"

CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3"

L10N="en-US"

INPUT_DEVICES="libinput wacom"

VIDEO_CARDS="amdgpu radeonsi"

QEMU_SOFTMMU_TARGETS="x86_64"
QEMU_USER_TARGETS="x86_64"

LC_MESSAGES=C
