#!/usr/bin/env sh

# Script to increase volume to 100 and display a notification
# Requires:
#	libnotify or dunstify
#	pulseaudio

app_name="Microphone Status"
summary="Volume Max"

pactl set-source-volume @DEFAULT_SOURCE@ 100%


sleep .01
if command -v dunstify; then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" \
		"$(pactl list sources | awk NR==10'{print $5}')"
else
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" \
		"$(pactl list sources | awk NR==10'{print $5}')"
fi
