Section "Device"
	Identifier			"AMD RX470"
	Driver				"amdgpu"
	Option	"SWcursor"		"False"
	Option	"Accel"			"True"
	Option	"ZaphodHeads"		"DisplayPort-0"
	Option	"DRI"			"3"
	Option	"EnablePageFlip"	"True"
	Option	"TearFree"		"True"
	Option	"AccelMethod"		"glamor"
	Option	"ShadowPrimary"		"False"
EndSection
