Section "InputClass"
        Identifier "joystick catchall"
        MatchIsJoystick "on"
        MatchDevicePath "/dev/input/event*"
        Driver "joystick"
        Option "StartKeysEnabled" "false"       #Disable mouse
        Option "StartMouseEnabled" "false"      #support
EndSection
