#!/usr/bin/env bash

. "${HOME}/.cache/wal/colors.sh"

export BARBOT_PID="$$"

geometry="1920x32+0+0"
font="Noto Mono:size=8"
jp_font="Noto Sans Mono CJK JP Regular:size=8"
sc_font="Noto Sans Mono CJK SC Regular:size=8"
kr_font="Noto Sans Mono CJK KR Regular:size=8"
emoji_font="Noto Color Emoji:size=8"
background_color="$color0"
foreground_color="$color15"

panel_fifo="/tmp/barbot-fifo"
if [ -e "$panel_fifo" ]
then
	rm "$panel_fifo"
	mkfifo "$panel_fifo"
else
	mkfifo "$panel_fifo"
fi


window_title() {
	echo "wt: $(xdotool getactivewindow getwindowname)"
}

quote() {
	echo 'qu: "I am that nigga entirely."'
}

mpd(){
	echo "mu: $(mpc current --wait)"
}

quote > "$panel_fifo" &

while true
do
	window_title
done > "$panel_fifo" &

while true
do
	mpd
done > "$panel_fifo" &

while read -r line
do
	case $line in
		wt:* ) wt="${line:4}" ;;
		qu:* ) qu="${line:4}" ;;
		mu:* ) mu="${line:4}" ;;
	esac
	echo "%{l}$wt %{c}$qu %{r}$mu" 
done < "$panel_fifo" | lemonbar -g "$geometry" -f "$font" -f "$jp_font" \
	-f "$sc_font" -f "$kr_font" -f "$emoji_font" -B "$background_color" \
	-F "$foreground_color" -b | sh
