#!/usr/bin/env sh

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config normal_border_color "${color8}"
bspc config active_border_color "${color1}"
bspc config focused_border_color "${color4}"
bspc config presel_feedback_color "${color2}"

bspc config border_width 4
bspc config window_gap 16
bspc config top_padding 32
bspc config right_padding 32
bspc config bottom_padding 32
bspc config left_padding 32

bspc config split_ratio 0.50
bspc config focus_follows_pointer true

bspc rule -a Chromium-browser-chromium desktop='^1'
bspc rule -a discord desktop='^2'
bspc rule -a Steam desktop='^3'
