#!/usr/bin/env bash

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config normal_border_color "${color8}"
bspc config active_border_color "${color2}"
bspc config focused_border_color "${color1}"
bspc config presel_feedback_color "${color3}"

bspc config border_width 4
bspc config window_gap 16
bspc config top_padding 32
bspc config right_padding 32
bspc config bottom_padding 32
bspc config left_padding 32
bspc config split_ratio 0.50

for i in {0..9}
do
	bspc desktop "^$i" -l monocle
done

bspc rule -a '*' state=floating
bspc rule -a Firefox:Navigator desktop='^1' state=tiled
bspc rule -a discord desktop='^1' state=tiled
bspc rule -a Steam desktop='^2'
