#!/usr/bin/env bash

prev_total=0
prev_idle=0

cicon="\\uf013"
while true
do 
	cpu=($(grep -m 1 'cpu' /proc/stat))
	idle=${cpu[4]}

	total=0
	for value in "${cpu[@]:1:8}"
	do
		total=$(( total + value ))
	done

	diff_idle=$(( idle - prev_idle ))
	diff_total=$(( total - prev_total ))
	diff_usage=$(( (1000 * (diff_total - diff_idle) / diff_total + 5) / 10 ))
	echo -e C$cicon $diff_usage%

	prev_total=$total
	prev_idle=$idle
	sleep 2
done
