audio_output {
	type		"pulse"
	name		"pa-pulseaudio"
	#format		"44100:16:2"
}

db_file			"~/data/mpd/database"
log_file		"~/tmp/logs/mpd.log"
music_directory		"~/mu"
playlist_directory	"~/mu/playlist"
pid_file		"/tmp/mpd-pid"
state_file		"~/tmp/cache/mpd-state"
sticker_file		"~/data/mpd/sticker.sql"
restore_paused		"yes"
bind_to_address		"localhost"
port			"6600"
auto_update		"yes"
