#!/usr/bin/env sh

rofi_prompt="Power Menu"
power_options="Poweroff Reboot Lock Sleep Hibernate Hybrid-Sleep"

confirmation() {
	rofi_confirmation_prompt="Are you sure? [$user_input]"
	user_input="$(printf "yes\\nno" | rofi -dmenu -p "$rofi_confirmation_prompt")"
	case $user_input in
		Y*|y*	) return ;;
		N*|n*	) exit ;;
	esac
}

user_input=$(echo "$power_options" | xargs -n1 | rofi -dmenu -p "$rofi_prompt")
case $user_input in
	Poweroff|poweroff|Shutdown|shutdown	) confirmation; loginctl poweroff -i ;;
	Reboot|reboot|Restart|restart		) confirmation; loginctl reboot -i ;;
	Lock|lock				) confirmation; "${HOME}/.dotfiles/powerscript/i3locck" ;;
	Sleep|sleep				) confirmation; "${HOME}/.dotfiles/powerscript/psleep" ;;
	Hibernate|hibernate			) confirmation; "${HOME}/.dotfiles/powerscript/phibernate" ;;
	Hybrid-Sleep|hybrid-sleep|Hybrid|hybrid	) confirmation; "${HOME}/.dotfiles/powerscript/phybrid-sleep" ;;
	*					) exit ;;
esac
