#!/usr/bin/env sh

rofi_prompt="Power Menu"
power_options="Poweroff Reboot Lock Sleep Hibernate Hybrid-Sleep"

confirmation() {
	rofi_confirmation_prompt="Are you sure? [$user_input]"
	user_input="$(printf "yes\\nno" | rofi -dmenu -p "$rofi_confirmation_prompt")"
	case $user_input in
		Y*|y*	) return ;;
		N*|n*	) exit ;;
	esac
}

user_input=$(echo "$power_options" | xargs -n1 | rofi -dmenu -p "$rofi_prompt")
case $user_input in
	Poweroff	) confirmation; loginctl poweroff -i ;;
	Reboot		) confirmation; loginctl reboot -i ;;
	Lock		) confirmation; "${HOME}/.dotfiles/powerscripts/i3locck" ;;
	Sleep		) confirmation; "${HOME}/.dotfiles/powerscripts/psleep" ;;
	Hibernate	) confirmation; "${HOME}/.dotfiles/powerscripts/phibernate" ;;
	Hybrid-Sleep	) confirmation; "${HOME}/.dotfiles/powerscripts/phybrid-sleep" ;;
	*		) exit 1 ;;
esac
