#!/usr/bin/env sh
# Notification Script for MPD

app_name="Audio Status"
icon="${HOME}/.dotfiles/notificationscripts/icons/audio.png"

speaker_volume="$(pactl list sinks | grep Volume | awk NR==1'{print $5}')"
speaker_mute="$(pactl list sinks | grep "Mute: yes")"

microphone_volume="$(pactl list sources | grep Volume | awk NR==1'{print $5}')"
microphone_mute="$(pactl list sources | grep Mute | awk NR==1 | grep yes)"

if [ "${speaker_mute}" = "Mute: yes" ]
then
	summary="Speakers: MUTED ${speaker_volume}"
else
	summary="Speakers: ${speaker_volume}"
fi

if [ "${microphone_mute}" = "Mute: yes" ]
then
	body="Microphone: MUTED ${microphone_volume}"
else
	body="Microphone: ${microphone_volume}"
fi

echo ${speaker_mute}
echo ${microphone_mute}
notify-send -a "${app_name}"\
	-i "${icon}"\
	-t 4000\
	"${summary}"\
	"${body}"
