#!/usr/bin/env sh

app_name="Time and Date (Local)"

summary="Time: $(date +'%R')"
body="Date: $(date +'%a %d %b %Y')"

if command -v dunstify
then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" \
		"${body}"
elif command -v notify-send
then
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" \
		"${body}"
else
	echo "dunstify/notify-send not found"
	exit 1
fi
