#!/usr/bin/env sh

XDG_SESSION_TYPE=x11

export XDG_SESSION_TYPE

[ -f "${XDG_CONFIG_HOME}/xorg/xresources" ] && xrdb -merge "${XDG_CONFIG_HOME}/xorg/xresources" &
[ -f "${XDG_CONFIG_HOME}/thm/current/Xresources" ] && xrdb -merge "${XDG_CONFIG_HOME}/thm/current/Xresources" &
xrandr -r 144 &

mpd &
syncthing -no-browser > "${HOME}/tmp/logs/syncthing.log" 2>&1 &
#parsecd app_daemon=1:app_silent=1:hidden=1 &

setroot --restore &
tint2 -c "${XDG_CONFIG_HOME}/thm/current/tint2rc-main" &
polybar bar1 --reload &
blugon -f &
"${HOME}/doc/setup/noti/music/music-changed" &

case $1 in
    bspwm|bsp ) exec bspwm ;;
    herbstluftwm|hlwm ) exec herbstluftwm --locked ;;
    openbox|ob ) exec openbox-session ;;
esac
