#!/usr/bin/env sh

XDG_SESSION_TYPE=x11

export XDG_SESSION_TYPE

[ -f "${HOME}/cfg/xorg/xresources" ] && xrdb "${HOME}/cfg/xorg/xresources"
[ -f "${HOME}/cfg/thm/current/Xresources" ] && xrdb -merge "${HOME}/cfg/thm/current/Xresources"
xrandr -r 144 &

mpd &
syncthing -no-browser > "${HOME}/tmp/logs/syncthing.log" 2>&1 &
#parsecd app_daemon=1:app_silent=1:hidden=1 &

setroot --restore &
tint2 -c "${XDG_CONFIG_HOME}/thm/current/tint2rc-main" &
polybar bar1 --reload &
blugon -f &
"${HOME}/doc/setup/bin/noti/music/music-changed" &

case $1 in
    openbox|ob ) exec openbox-session ;;
    cwm ) exec cwm -c "${HOME}/cfg/cwm/cwmrc" ;;
esac
