;;; thm-theme.el --- template for emacs theme to be used with thm

;;; Commentary:
;; thm template for Emacs

;;; Code:
(deftheme thm
  "Emacs theme generated by thm using a template.")

(let ((bg_color "#efefef")
      (fg_color "#1f1f1f")
      (color0 "#efefef")
      (color1 "#e67b7b")  ; red
      (color2 "#80ba63")  ; green
      (color3 "#f5a868")  ; yellow
      (color4 "#849ce6")  ; blue
      (color5 "#b37fe3")  ; magenta
      (color6 "#6ebdc4")  ; cyan
      (color7 "#3f3f3f")
      (color8 "#b0b0b0")
      (color9 "#ed9a9a")  ; red
      (color10 "#a3d989") ; green
      (color11 "#f7c297") ; yellow
      (color12 "#a6baf5") ; blue
      (color13 "#d1adf2") ; magenta
      (color14 "#bedcde") ; cyan
      (color15 "#1f1f1f"))
  (custom-theme-set-faces
   'thm

   `(Info-quoted ((t (:background ,bg_color :foreground ,color7))))
   `(bold ((t (:bold t :background ,bg_color :foreground ,fg_color))))
   `(bold-italic ((t (:bold t :italic t :background ,bg_color :foreground ,fg_color))))
   `(border ((t (:foreground ,color8))))
   `(buffer-menu-buffer ((t (:bold t :background ,bg_color :foreground ,fg_color))))
   `(button ((t (:underline t :background ,bg_color :foreground ,color12))))
   
   `(default ((t (:background ,bg_color :foreground ,fg_color))))
   `(italic ((t (:italic t :background ,bg_color :foreground ,fg_color))))
   `(fringe ((t (:background ,bg_color :foreground ,fg_color))))
   `(vertical-border ((t (:foreground ,color8))))
   `(mode-line ((t (:box nil :background ,fg_color :foreground ,bg_color))))
   `(mode-line-inactive ((t (:box nil :background ,color8 :foreground ,color7))))
   `(cursor ((t (:background ,fg_color :foreground ,fg_color))))
   ))

(provide-theme 'thm)
;;; thm-theme.el ends here
