# created by eselect-repo
[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git


[libressl]
location = /var/db/repos/libressl
sync-type = git
sync-uri = https://anongit.gentoo.org/git/repo/proj/libressl.git
