# created by eselect-repo

[musl]
location = /var/db/repos/musl
sync-type = git
sync-uri = git://anongit.gentoo.org/proj/musl.git

[libressl]
location = /var/db/repos/libressl
sync-type = git
sync-uri = git://anongit.gentoo.org/repo/proj/libressl.git

[gentoo-clang]
location = /var/db/repos/gentoo-clang
sync-type = git
sync-uri = https://github.com/BilyakA/gentoo-clang.git

[smaeul]
location = /var/db/repos/smaeul
sync-type = git
sync-uri = https://github.com/smaeul/portage-overlay.git

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://anongit.gentoo.org/git/repo/proj/guru.git
