#!/usr/bin/env sh

# Script to mute volume and display a notification
# Requires:
#	libnotify or dunstify
#	pulseaudio

app_name="Speaker Status"
summary="Volume Toggle"

pactl set-sink-mute @DEFAULT_SINK@ toggle

if command -v dunstify; then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" \
		"Mute: $(pactl list sinks | awk NR==9'{print $2}')"
else
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" \
		"Mute: $(pactl list sinks | awk NR==9'{print $2}')"
fi
