#!/usr/bin/env bash
# Lemonbar Config

. ${HOME}/.cache/wal/colors.sh

geometry="1920x26+0+0"
background_color="${color7}"
foreground_color="${color0}"
font="Noto Sans Mono:size=8"
#fonttc="Noto Sans Mono CJK TC:size=8"
#fontkr="Noto Sans Mono CJK KR:size=8"
#fontsc="Noto Sans Mono CJK SC:size=8"
fontjp="Noto Sans Mono CJK JP:size=8"
fontem="Noto Emoji:size=8"
icon="Font Awesome 5 Free:style=Solid:size=8"

bcolor0="%{F${color0}}"
bcolor1="%{F${color1}}"
bcolor2="%{F${color2}}"
bcolor3="%{F${color3}}"
bcolor4="%{F${color4}}"
bcolor5="%{F${color5}}"
bcolor6="%{F${color6}}"
bcolor7="%{F${color7}}"
bcolor8="%{F${color8}}"
bcreset="%{F-}"

bmpd() {

	echo -e "${bcolor1}\uf001${bcreset}  $(mpc current)"
}

bvol() {
	ovol=""
	mvol="$(pamixer --get-mute)"

	if ${mvol} -eq true; then
		ovol="${bcolor1}\uf026${bcreset}"
	else
		ovol="${bcolor1}\uf028${bcreset}"
	fi

	echo -e ${ovol}
}

bmic() {
	omic=""
	mmic="$(pamixer --source 1 --get-mute)"

	if ${mmic} -eq true; then
		omic="${bcolor1}\uf131${bcreset}"
	else
		omic="${bcolor1}\uf130${bcreset}"
	fi

	echo -e ${omic}
}

btime() {
	echo -e "${bcolor1}\uf017${bcreset}  $(date +'%R:%S')"
}

bdate() {
	echo -e "${bcolor1}\uf133${bcreset}  $(date +'%a %d %b %Y')"
}

bar() {
	while true
	do
		printf "%s\n" "    $(bdate) %{c}$(bvol)      $(bmpd)      $(bmic) %{r}$(btime)    "
		sleep 0.5
	done
}

bar | lemonbar -g "${geometry}" -f "${font}" -f "${icon}" -f "${fonttc}" -f "${fontkr}" -f "${fontsc}" -f "${fontjp}" -f "${fontem}" -B "${background_color}" -F "${foreground_color}" -p
