#!/usr/bin/env bash
# Lemonbar Config

. "${HOME}/.cache/wal/colors.sh"

geometry="1920x26+0+0"

background_color="${color7}"
foreground_color="${color0}"
bcolor0="%{F${color0}}"
bcolor1="%{F${color1}}"
bcolor2="%{F${color2}}"
bcolor3="%{F${color3}}"
bcolor4="%{F${color4}}"
bcolor5="%{F${color5}}"
bcolor6="%{F${color6}}"
bcolor7="%{F${color7}}"
bcolor8="%{F${color8}}"
bcreset="%{F-}"

font="Noto Sans Mono:size=8"
fontsc="Noto Sans Mono CJK SC:size=8"
fontkr="Noto Sans Mono CJK KR:size=8"
fontjp="Noto Sans Mono CJK JP:size=8"
icon="Font Awesome 5 Free:style=Solid:size=8"

bmpd() {
	if [[ $(mpc current) ]]; then
		if mpc status | grep -q paused; then
			ompd="${bcolor3}\\uf04c${bcreset} $(mpc current)"
		else
			ompd="${bcolor3}\\uf001${bcreset} $(mpc current)"
		fi
	else
		ompd="${bcolor3}\\uf001${bcreset} MPD n/a"
	fi

	echo -e "${ompd}"
}

bvol() {
	mvol="$(pamixer --get-mute)"

	if ${mvol} -eq true; then
		ovol="${bcolor3}\\uf026${bcreset}"
	else
		ovol="${bcolor3}\\uf028${bcreset}"
	fi

	echo -e "${ovol}"
}

bmic() {
	mmic="$(pamixer --source 0 --get-mute)"

	if ${mmic} -eq true; then
		omic="${bcolor3}\\uf131${bcreset}"
	else
		omic="${bcolor3}\\uf130${bcreset}"
	fi

	echo -e "${omic}"
}

btime() {
	echo -e "${bcolor3}\\uf017${bcreset}  $(date +'%R')"
}

bdate() {
	echo -e "${bcolor3}\\uf133${bcreset}  $(date +'%a %d %b %Y')"
}

bar() {
	while true
	do
		printf '%s\n' "    $(bdate) %{c}$(bvol)      $(bmpd)      $(bmic) %{r}$(btime)    "
		sleep 0.5
	done
}
bar | lemonbar -g "${geometry}" -f "${font}" -f "${icon}" -f "${fontkr}" -f "${fontjp}" -f "${fontsc}" -B "${background_color}" -F "${foreground_color}" -p
