#!/usr/bin/env bash

. "${HOME}/.cache/wal/colors.sh"
if [[ $(pidof sxhkd)  ]]; then
	kill $(pidof sxhkd)
	sxhkd &
else
	sxhkd &
fi

if [[ $(pidof lemonbar) ]]; then
	kill $(pidof lemonbar)
	${HOME}/.dotfiles/dotconfig/bspwm/bar &
else
	${HOME}/.dotfiles/dotconfig/bspwm/bar &
fi

xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color1"

bspc config border_width 6
bspc config window_gap 20

bspc config top_padding 142
bspc config bottom_padding 116
bspc config left_padding 130
bspc config right_padding 130

bspc config -d ^1 top_padding -116
bspc config -d ^1 bottom_padding -116
bspc config -d ^1 left_padding -130
bspc config -d ^1 right_padding -130
bspc config -d ^1 window_gap 10

bspc config -d ^2 top_padding -116
bspc config -d ^2 bottom_padding -116
bspc config -d ^2 left_padding -130
bspc config -d ^2 right_padding -130
bspc config -d ^2 window_gap 10

#bspc config top_padding 80
#bspc config bottom_padding 80
#bspc config left_padding 338
#bspc config right_padding 338
#bspc config -d ^1 left_padding -138
#bspc config -d ^1 right_padding -138
#bspc config -d ^2 left_padding -138
#bspc config -d ^2 right_padding -138

bspc config split_ratio 0.50
bspc config focus_follows_pointer true

bspc rule -a "Firefox" desktop='^1'
bspc rule -a "discord" desktop='^2'
bspc rule -a "Steam" desktop='^3' state=floating
bspc rule -a "keepassxc" state=floating
