#!/usr/bin/env sh

. "${HOME}/.cache/wal/colors.sh"
sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color1"

bspc config border_width 6
bspc config window_gap 20

bspc config top_padding 50
bspc config bottom_padding 50
bspc config left_padding 50
bspc config right_padding 50

#bspc config top_padding 80
#bspc config bottom_padding 80
#bspc config left_padding 338
#bspc config right_padding 338

#bspc config -d ^1 left_padding -138
#bspc config -d ^1 right_padding -138

#bspc config -d ^2 left_padding -138
#bspc config -d ^2 right_padding -138

bspc config split_ratio 0.50
bspc config focus_follows_pointer true

bspc rule -a "Firefox" desktop='^1'
bspc rule -a "discord" desktop='^2'
bspc rule -a "Steam" desktop='^3' state=floating
bspc rule -a "keepassxc" state=floating
