#!/usr/bin/env sh

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV V

bspc config normal_border_color "$color8"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color1"

bspc config border_width 4
bspc config window_gap 16

bspc config top_padding 128
bspc config bottom_padding 128
bspc config left_padding 256
bspc config right_padding 256

bspc config -d ^1 top_padding -128
bspc config -d ^1 bottom_padding -128
bspc config -d ^1 left_padding -256
bspc config -d ^1 right_padding -256
bspc config -d ^1 window_gap 16

bspc config split_ratio 0.50
bspc config focus_follows_pointer true

#bspc rule -a "*" state=floating
bspc rule -a "Firefox" desktop='^1' border=off
bspc rule -a "discord" desktop='^2'
bspc rule -a "keepassxc" state=floating
