#!/usr/bin/env bash
# Lemonbar Config

. "${HOME}/.cache/wal/colors.sh"

geometry="1900x32+10+10"

background_color="${color0}"
foreground_color="${color7}"

iconcol="%{F${color5}}"
bcolor0="%{F${color0}}"
bcolor1="%{F${color1}}"
bcolor2="%{F${color2}}"
bcolor3="%{F${color3}}"
bcolor4="%{F${color4}}"
bcolor5="%{F${color5}}"
bcolor6="%{F${color6}}"
bcolor7="%{F${color7}}"
bcolor8="%{F${color8}}"
cclear="%{F-}"

font="Noto Sans Mono:pixelsize=12"
fontsc="Noto Sans Mono CJK SC:pixelsize=12"
fontkr="Noto Sans Mono CJK KR:pixelsize=12"
fontjp="Noto Sans Mono CJK JP:pixelsize=12"
iconfont="Font Awesome 5 Free:style=Solid:pixelsize=16"

bmpd()
{
	song="$(mpc current)"
	song_status="$(mpc status | awk -F "[] []" NR==2'{print $2}')"

	play_icon="\\uf001"
	pause_icon="\\uf04c"

	play_color="${bcolor7}"
	pause_color="${bcolor4}"

	output="MPD N/A"

	if [[ "${song_status}" == "paused" ]]
	then
		output="${iconcol}${pause_icon}${cclear}  ${pause_color}${song}${cclear}"
	else
		output="${iconcol}${play_icon}${cclear}  ${play_color}${song}${cclear}"
	fi

	echo -e "${output}"
}

bvol()
{
	mvol="$(pamixer --get-mute)"

	icon="\\uf028"
	icon_mute="\\uf026"

	output=""

	if ${mvol} -eq true; then
		output="${iconcol}${icon_mute}${cclear}"
	else
		output="${iconcol}${icon}${cclear}"
	fi

	echo -e "${output}"
}

bmic()
{
	mmic="$(pamixer --source 0 --get-mute)"

	icon="\\uf130"
	icon_mute="\\uf131"

	output=""

	if ${mmic} -eq true; then
		output="${iconcol}${icon_mute}${cclear}"
	else
		output="${iconcol}${icon}${cclear}"
	fi

	echo -e "${output}"
}

btime()
{
	icon="\\uf017"

	echo -e "${bcolor5}${icon}${cclear}  $(date +'%R')"
}

bdate()
{
	icon="\\uf133"

	echo -e "${bcolor5}${icon}${cclear}  $(date +'%a %d %b %Y')"
}

bar()
{
	while true
	do
		printf '%s\n' "  $(bdate) %{c}$(bvol)      $(bmpd)      $(bmic) %{r}$(btime)  "
		sleep 0.5
	done
}

bar | lemonbar -p -g "${geometry}"\
	-f "${font}"\
	-f "${iconfont}"\
	-f "${fontkr}"\
	-f "${fontjp}"\
	-f "${fontsc}"\
	-B "${background_color}"\
	-F "${foreground_color}"
