#!/usr/bin/env sh

# Script to increase mpd volume and display a notification
# Requires:
#	libnotify or dunstify
#	mpd
#	mpc

app_name="MPD Status"
summary="Volume Up"

mpc volume +2

if command -v dunstify; then
	dunstify -a "${app_name}" \
		-t 4000 \
		-r 13596705 \
		"${summary}" \
		"$(mpc volume | awk '{print $2}')"
else
	notify-send -t 4000 \
		-a "${app_name}" \
		"${summary}" \
		"$(mpc volume | awk '{print $2}')"
fi
