#!/usr/bin/env sh

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV V VI VII VIII

bspc config normal_border_color "$color8"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color1"

bspc config border_width 4
bspc config window_gap 16

bspc config top_padding 128
bspc config bottom_padding 128
bspc config left_padding 256
bspc config right_padding 256

bspc config -d ^1 top_padding -128
bspc config -d ^1 bottom_padding -128
bspc config -d ^1 left_padding -256
bspc config -d ^1 right_padding -256
bspc config -d ^1 window_gap 16

bspc config -d ^6 top_padding -128
bspc config -d ^6 bottom_padding -128
bspc config -d ^6 left_padding -256
bspc config -d ^6 right_padding -256
bspc config -d ^6 window_gap 16

bspc config -d ^7 top_padding -128
bspc config -d ^7 bottom_padding -128
bspc config -d ^7 left_padding -256
bspc config -d ^7 right_padding -256
bspc config -d ^7 window_gap 0
bspc config -d ^7 border_width 2

bspc config -d ^8 top_padding -128
bspc config -d ^8 bottom_padding -128
bspc config -d ^8 left_padding -256
bspc config -d ^8 right_padding -256
bspc config -d ^8 window_gap 16

bspc config split_ratio 0.50
bspc config focus_follows_pointer true

#bspc rule -a "*" state=floating
bspc rule -a "Firefox" desktop='^1'
bspc rule -a "discord" desktop='^6'
bspc rule -a "Steam" desktop='^8'
