# created by eselect-repo

[ahrs]
location = /var/db/repos/ahrs
sync-type = git
sync-uri = https://gitlab.com/ahrs/gentoo-stuff.git

[hering-overlay]
location = /var/db/repos/hering-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/hering-overlay.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/steam-overlay.git

[go-overlay]
location = /var/db/repos/go-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/go-overlay.git

[rust]
location = /var/db/repos/rust
sync-type = git
sync-uri = https://github.com/gentoo-mirror/rust.git

[libressl]
location = /var/db/repos/libressl
sync-type = git
sync-uri = https://github.com/gentoo-mirror/libressl.git



[wizard]
location = /var/db/repos/wizard
sync-type = git
sync-uri = https://github.com/gentoo-mirror/wizard.git

[vampire]
location = /var/db/repos/vampire
sync-type = git
sync-uri = https://github.com/gentoo-mirror/vampire.git

[4nykey]
location = /var/db/repos/4nykey
sync-type = git
sync-uri = https://github.com/gentoo-mirror/4nykey.git
