# created by eselect-repo

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/steam-overlay.git


[ahrs]
location = /var/db/repos/ahrs
sync-type = git
sync-uri = https://gitlab.com/ahrs/gentoo-stuff.git


[ricerlay]
location = /var/db/repos/ricerlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/ricerlay.git




[hering-overlay]
location = /var/db/repos/hering-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/hering-overlay.git





[libressl]
location = /var/db/repos/libressl
sync-type = git
sync-uri = https://github.com/gentoo-mirror/libressl.git
