# created by eselect-repo
[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[libressl]
location = /var/db/repos/libressl
sync-type = git
sync-uri = https://github.com/gentoo/libressl.git

[hering-overlay]
location = /var/db/repos/hering-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/hering-overlay.git

[vampire]
location = /var/db/repos/vampire
sync-type = git
sync-uri = https://github.com/gentoo-mirror/vampire.git
