# Load Plugin Manager
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# Plugins
plug "whereswaldon/shellcheck.kak"

# kak-lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(go|lua|python|rust) lsp-enable-window

# Template Command
define-command -params 1 -docstring \
"Print template into the current file. Templates are located at %val{config}/templates." \
template %{
	evaluate-commands %sh{
		[ -e "$kak_config/templates/$1" ] && \
			printf '%s\n' "exec !cat<space>$kak_config/templates/$1<ret>" || \
			printf '%s\n' "echo Template $1 doesn't exist."
	}
}

# Keybinds
map global user l ':enter-user-mode lsp<ret>' -docstring 'Enter kak-lsp user mode'
map global user p '!wl-paste<ret>' -docstring 'Paste from System Clipboard (Wayland)'
map global user y '<a-|>wl-copy<ret>' -docstring 'Copy to System Clipboard (Wayland)'

# Enable Wrapping
add-highlighter global/ wrap -indent -marker '$>'

# Highlight Matching Characters
add-highlighter global/ show-matching

# Indentation Options
set-option global indentwidth 0
set-option global tabstop 8
hook global WinSetOption filetype=(css|html|xml) %{
	map global insert <tab> '  '
	set-option global indentwidth 2
}
hook global WinSetOption filetype=python %{
	map global insert <tab> '    '
	set-option global indentwidth 4
}

# Colorscheme
evaluate-commands %sh{
	[ "$TERM" = linux ] && return 0
	. $(cat $HOME/tmp/cache/thm/current_thm)
	case $theme_type in
		light ) printf '%s\n' "colorscheme theme-light" ;;
		dark ) printf '%s\n' "colorscheme theme-dark" ;;
		* ) ;;
	esac
}
