#!/usr/bin/env bash

# Config file for Herbstluftwm

# shellcheck source=/home/yemou/.cache/wal/colors.sh
. "${HOME}/.cache/wal/colors.sh"

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all
mod=Mod4

hc keybind XF86AudioNext	spawn mpc next
hc keybind XF86AudioPrev	spawn mpc prev
hc keybind Mod1-XF86AudioPrev	spawn mpc seek 0%
hc keybind XF86AudioPlay	spawn "${HOME}/.dotfiles/noti/music/music-toggle"
hc keybind XF86AudioStop	spawn "${HOME}/.dotfiles/noti/music/music-stop"
hc keybind XF86Mail 		spawn "${HOME}/.dotfiles/noti/music/music-info"
hc keybind $mod-Shift-Up	spawn "${HOME}/.dotfiles/noti/music/music-volume-up"
hc keybind $mod-Shift-Down	spawn "${HOME}/.dotfiles/noti/music/music-volume-down"

hc keybind Shift-XF86AudioRaiseVolume	spawn "${HOME}/.dotfiles/noti/volume/speaker-volume-up-all"
hc keybind XF86AudioRaiseVolume		spawn "${HOME}/.dotfiles/noti/volume/speaker-volume-up"
hc keybind XF86AudioLowerVolume		spawn "${HOME}/.dotfiles/noti/volume/speaker-volume-down"
hc keybind XF86AudioMute		spawn "${HOME}/.dotfiles/noti/volume/speaker-volume-mute"
hc keybind XF86Tools			spawn "${HOME}/.dotfiles/noti/volume/volume-info"

hc keybind Mod1-Control-XF86AudioRaiseVolume	spawn "${HOME}/.dotfiles/noti/volume/microphone-please-die"
hc keybind Mod1-Shift-XF86AudioRaiseVolume	spawn "${HOME}/.dotfiles/noti/volume/microphone-volume-up-all"
hc keybind Mod1-XF86AudioRaiseVolume		spawn "${HOME}/.dotfiles/noti/volume/microphone-volume-up"
hc keybind Mod1-XF86AudioLowerVolume		spawn "${HOME}/.dotfiles/noti/volume/microphone-volume-down"
hc keybind $mod-e				spawn "${HOME}/.dotfiles/noti/volume/microphone-volume-mute"

hc keybind Print	spawn sh -c "curl -F"file=@$(nougat -f)" https://0x0.st | xclip -selection clipboard"
hc keybind $mod-Print	spawn sh -c "curl -F"file=@$(nougat)" https://0x0.st | xclip -selection clipboard"
hc keybind $mod-r	spawn rofi -show run

hc keybind $mod-Return		spawn alacritty
hc keybind $mod-t		spawn "${HOME}/.dotfiles/noti/time-date/utc-time-date"
hc keybind $mod-Control-t	spawn "${HOME}/.dotfiles/noti/time-date/local-time-date"

hc keybind $mod-Control-q	quit
hc keybind $mod-Control-r	reload

hc keybind $mod-m	set_layout max
hc keybind $mod-d	remove
hc keybind $mod-Shift-s	floating toggle
hc keybind $mod-Shift-f	fullscreen toggle
hc keybind $mod-Shift-p	pseudotile toggle

hc keybind $mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

hc keybind $mod-h	focus left
hc keybind $mod-j	focus down
hc keybind $mod-k	focus up
hc keybind $mod-l	focus right

hc keybind $mod-Shift-h	shift left
hc keybind $mod-Shift-j	shift down
hc keybind $mod-Shift-k	shift up
hc keybind $mod-Shift-l	shift right

hc keybind $mod-u	split left 0.5
hc keybind $mod-i	split bottom 0.5
hc keybind $mod-o	split top 0.5
hc keybind $mod-p	split right 0.5
hc keybind $mod-s	split explode

hc keybind $mod-q	close

resizestep=0.025
hc keybind $mod-Shift-u       resize left +$resizestep
hc keybind $mod-Shift-i       resize down +$resizestep
hc keybind $mod-Shift-o       resize up +$resizestep
hc keybind $mod-Shift-p       resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $mod-period use_index +1 --skip-visible
hc keybind $mod-comma  use_index -1 --skip-visible

# mouse
hc mouseunbind --all
hc mousebind $mod-Button1 move
hc mousebind $mod-Button2 zoom
hc mousebind $mod-Button3 resize

# focus
hc keybind $mod-BackSpace   cycle_monitor
hc keybind $mod-Tab         cycle_all +1
hc keybind $mod-Shift-Tab   cycle_all -1
hc keybind $mod-c cycle
#hc keybind $mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
