#!/usr/bin/env bash

. "${HOME}/.cache/wal/colors.sh"

hc() { herbstclient "$@"; }

hc emit_hook reload

hc keyunbind --all
mod=Mod4

hc keybind XF86AudioNext	spawn mpc next
hc keybind XF86AudioPrev	spawn mpc prev
hc keybind Mod1-XF86AudioPrev	spawn mpc seek 0%
hc keybind XF86AudioPlay	spawn "${HOME}/.dotfiles/noti/music/music-toggle"
hc keybind XF86AudioStop	spawn "${HOME}/.dotfiles/noti/music/music-stop"
hc keybind XF86Mail 		spawn "${HOME}/.dotfiles/noti/music/music-info"
hc keybind $mod-Shift-Up	spawn "${HOME}/.dotfiles/noti/music/music-volume-up"
hc keybind $mod-Shift-Down	spawn "${HOME}/.dotfiles/noti/music/music-volume-down"

hc keybind Shift-XF86AudioRaiseVolume	spawn "${HOME}/.dotfiles/noti/volume/speaker-volume-up-all"
hc keybind XF86AudioRaiseVolume		spawn "${HOME}/.dotfiles/noti/volume/speaker-volume-up"
hc keybind XF86AudioLowerVolume		spawn "${HOME}/.dotfiles/noti/volume/speaker-volume-down"
hc keybind XF86AudioMute		spawn "${HOME}/.dotfiles/noti/volume/speaker-volume-mute"
hc keybind XF86Tools			spawn "${HOME}/.dotfiles/noti/volume/volume-info"

hc keybind Mod1-Control-XF86AudioRaiseVolume	spawn "${HOME}/.dotfiles/noti/volume/microphone-please-die"
hc keybind Mod1-Shift-XF86AudioRaiseVolume	spawn "${HOME}/.dotfiles/noti/volume/microphone-volume-up-all"
hc keybind Mod1-XF86AudioRaiseVolume		spawn "${HOME}/.dotfiles/noti/volume/microphone-volume-up"
hc keybind Mod1-XF86AudioLowerVolume		spawn "${HOME}/.dotfiles/noti/volume/microphone-volume-down"
hc keybind $mod-e				spawn "${HOME}/.dotfiles/noti/volume/microphone-volume-mute"

hc keybind $mod-t		spawn "${HOME}/.dotfiles/noti/time-date/local-time-date"
hc keybind $mod-Control-t	spawn "${HOME}/.dotfiles/noti/time-date/utc-time-date"

hc keybind Print	spawn nougat -tcf
hc keybind $mod-Print	spawn nougat -tc
hc keybind Pause	spawn killall -SIGUSR1 dunst
hc keybind $mod-Pause	spawn killall -SIGUSR2 dunst
hc keybind $mod-r	spawn rofi -show run
hc keybind $mod-Return	spawn alacritty

hc keybind $mod-Control-q	quit
hc keybind $mod-Control-r	reload

hc keybind $mod-m	cycle_layout +1 max horizontal
hc keybind $mod-d	remove
hc keybind $mod-Shift-s	floating toggle
hc keybind $mod-Shift-f	fullscreen toggle
hc keybind $mod-Shift-p	pseudotile toggle

hc keybind $mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 horizontal vertical horizontal grid    \
               , cycle_layout +1

hc keybind $mod-h		focus left
hc keybind $mod-j		focus down
hc keybind $mod-k		focus up
hc keybind $mod-l		focus right
hc keybind $mod-Tab		cycle_all +1
hc keybind $mod-Shift-Tab	cycle_all -1

hc keybind $mod-Shift-h	shift left
hc keybind $mod-Shift-j	shift down
hc keybind $mod-Shift-k	shift up
hc keybind $mod-Shift-l	shift right

hc keybind $mod-u	split left 0.5
hc keybind $mod-i	split bottom 0.5
hc keybind $mod-o	split top 0.5
hc keybind $mod-p	split right 0.5
hc keybind $mod-s	split explode

hc keybind $mod-q	close

resizestep=0.025
hc keybind $mod-Shift-u       resize left +$resizestep
hc keybind $mod-Shift-i       resize down +$resizestep
hc keybind $mod-Shift-o       resize up +$resizestep
hc keybind $mod-Shift-p       resize right +$resizestep

tag_names=( {1..10} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$mod-$key" use_index "$i"
        hc keybind "$mod-Shift-$key" move_index "$i"
    fi
done

if hc silent new_attr bool my_first_start ; then
	hc load 1 '(clients max:0)'
	hc load 2 '(clients horizontal:0)'
	hc load 3 '(clients max:0)'
	hc load 4 '(clients horizontal:0)'
	hc load 5 '(clients max:0)'
	hc load 6 '(split horizontal:0.500000:0
	(split vertical:0.500000:1
	(clients horizontal:0)
	(clients horizontal:0))
	(split vertical:0.500000:1
	(clients horizontal:0)
	(clients horizontal:0)))'
	hc load 7 '(clients horizontal:0)'
	hc load 8 '(clients horizontal:0)'
	hc load 9 '(clients horizontal:0)'
	hc load 10 '(clients horizontal:0)'
fi


hc keybind $mod-period use_index +1 --skip-visible
hc keybind $mod-comma  use_index -1 --skip-visible

hc mouseunbind --all
hc mousebind $mod-Button1 move
hc mousebind $mod-Button2 zoom
hc mousebind $mod-Button3 resize

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color "${color0}"
hc set frame_border_normal_color "${color0}"
hc set frame_bg_normal_color "${color0}"
hc set frame_bg_active_color "${color0}"
hc set frame_border_width 2
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 4
hc set frame_gap 16

hc attr theme.active.color "${color0}"
hc attr theme.normal.color "${color0}"
hc attr theme.urgent.color "${color0}"
hc attr theme.inner_width 4
hc attr theme.inner_color "${color7}"
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color "${color7}"
hc attr theme.active.inner_color "${color4}"
hc attr theme.active.outer_color "${color5}"
hc attr theme.background_color "${color7}"

hc pad 0 32 32 32 32
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

hc unrule -F
hc rule class=Chromium-browser-chromium tag=1
hc rule class=Firefox tag=1
hc rule class=Steam tag=3
hc rule class=discord tag=2
hc rule focus=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc unlock
herbstclient set tree_style '╾│ ├└╼─┐'
