#!/bin/sh

# Make sure we don't miss any important setup
[ -d /etc/X11/xinit/xinitrc.d ] && {
    for s in /etc/X11/xinit/xinitrc.d/*
    do
	[ -x "$s" ] && . $s
    done
    unset s
}

# Let dbus services see custom xdg home dirs
dbus_uae=dbus-update-activation-environment
command -v $dbus_uae && \
    $dbus_uae XDG_DATA_HOME XDG_CONFIG_HOME XDG_CACHE_HOME

# Set XDG_SESSION_TYPE
export XDG_SESSION_TYPE=x11

# Load xresources
[ -f "${XDG_CONFIG_HOME}/xorg/xresources" ] && xrdb "${XDG_CONFIG_HOME}/xorg/xresources"
[ -f "${XDG_CACHE_HOME}/thm/Xresources" ] && xrdb -merge "${XDG_CONFIG_HOME}/thm/current/Xresources"

xrandr -r 144 & # Set monitor refresh rate to 144hz
xrandr --output DisplayPort-0 --set TearFree on # Make sure TearFree is enabled

# Autostart applications
blugon & # Launch blue light filter
setroot --restore & # Restore wallpeper
tint2 -c "${XDG_CONFIG_HOME}/thm/current/tint2rc-main" & # Launch bottom bar
polybar bar1 --reload & # Launch top bar
notimusic changed & # Display when new song is playing

# Pick a Window Manager/Desktop Environment to enter
case $1 in
    openbox|ob ) exec openbox-session ;;
    cwm ) exec cwm -c "${HOME}/cfg/cwm/cwmrc" ;;
esac
